
//.---------------------------
//----Data------
export const DATA_LOAD_USER = "DATA_LOAD_USER"
export const DATA_LOAD_ROUTE_MGMT_DATA = "DATA_LOAD_ROUTE_MGMT_DATA"
export const DATA_LOAD_INPUT_SCREEN = "DATA_LOAD_INPUT_SCREEN"
export const DATA_UPDATE_COMPONENTS_ORDER = "UPDATE_COMPONENTS_ORDER"
export const DATA_UPDATE_HTYPE_ORDER = "DATA_UPDATE_HTYPE_ORDER"
export const DATA_UPDATE_CHILD_HTYPE_ORDER = "DATA_UPDATE_CHILD_HTYPE_ORDER"
export const DATA_UPDATE_COMPONENT = "DATA_UPDATE_COMPONENT"
export const DATA_ADD_NEW_COMPONENT = "DATA_ADD_NEW_COMPONENT"
export const DATA_EMPTY_SELECTED_COMPONENT_ID = "DATA_EMPTY_SELECTED_COMPONENT_ID"
export const DATA_HANDLE_HTYPE_CHANGE = "DATA_HANDLE_HTYPE_CHANGE"
export const DATA_SET_SELECTED_COMPONENT = "DATA_SET_SELECTED_COMPONENT"
export const DATA_LOAD_COMPONENTS = "DATA_LOAD_COMPONENTS"
export const DATA_SET_SELECTED_HTYPE = "DATA_SET_SELECTED_HTYPE"
export const DATA_DELETE_SELECTED_COMPONENT = "DATA_DELETE_SELECTED_COMPONENT"
//-----UI-------
export const UI_UPDATE_ROUTEMGMT_STATE = "UI_UPDATE_ROUTEMGMT_STATE"
export const UI_LOAD_STOP_AND_POI_MANAGER_STATE = "UI_LOAD_STOP_AND_POI_MANAGER_STATE"
export const UI_UPDATE_INPUT_SCREEN_STATE = "UI_UPDATE_INPUT_SCREEN_STATE";
export const UI_UPDATE_SIMULATOR_SELECTION_STATE = "UI_UPDATE_SIMULATOR_SELECTION_STATE";
export const UI_UPDATE_SELECTOR_MANAGER_STATE = "UI_UPDATE_SELECTOR_MANAGER_STATE";
export const UI_INITIALIZE_INPUT_SCREEN_UI = "UI_INITIALIZE_INPUT_SCREEN_UI";
export const UI_UPDATE_SIMULATOR_SELECTION = "UI_UPDATE_SIMULATOR_SELECTION"
export const UI_UPDATE_ROUTE_STATE = "UI_UPDATE_ROUTE_STATE";
export const UI_STOP_AND_POI_MANAGER_CONTROLLER = "UI_STOP_AND_POI_MANAGER_CONTROLLER";
export const UI_SET_TITLE = "UI_SET_TITLE";
export const UI_INITIALIZE_SIMULATOR_STATE = "UI_INITIALIZE_SIMULATOR_STATE";
export const UI_UPDATE_INPUT_SCREEN_FLAG = "UI_UPDATE_INPUT_SCREEN_FLAG"
