export const REMOVE_ROUTE = "REMOVE_ROUTE";
export const UPDATE_ROUTE_STATE = "UPDATE_ROUTE_STATE";
export const UPDATE_SELECTOR_MANAGER_STATE = "UPDATE_SELECTOR_MANAGER_STATE";

export const INITIALIZE_INPUT_SCREEN_UI = "INITIALIZE_INPUT_SCREEN_UI";
export const HEADLINE = "HEADLINE";
export const INITIALIZE_HTYPE = "INITIALIZE_HTYPE";
export const DELETE_HTYPE = "DELETE_HTYPE"
export const EMPTY_SELECTED_COMPONENT_ID = "EMPTY_SELECTED_COMPONENT_ID"
export const UPDATE_SIMULATOR_SELECTION = "UPDATE_SIMULATOR_SELECTION"
export const SET_SELECTED_COMPONENT = "SET_SELECTED_COMPONENT"
export const UPDATE_COMPONENTS_ORDER = "UPDATE_COMPONENTS_ORDER"
export const CLEAN_NONSAVED_HTYPES = "CLEAN_NONSAVED_HTYPES"
export const STOP_AND_POI_MANAGER_CONTROLLER = "STOP_AND_POI_MANAGER_CONTROLLER"
export const SET_TITLE = "SET_TITLE"
export const LOAD_USER = "LOAD_USER"
export const CLEAN_USER = "CLEAN_USER"
export const LOAD_HTYPE_DATA = "LOAD_HTYPE_DATA"
export const INITIALIZE_INPUTSCREEN = "INITIALIZE_INPUTSCREEN"
//.---------------------------
//----Data------
export const INITIALIZE_INPUTSCREEN_DATA = "INITIALIZE_INPUTSCREEN_DATA"
export const LOAD_ROUTEMGMT_DATA = "LOAD_ROUTEMGMT_DATA"
export const LOAD_INPUTSCREEN_DATA = "LOAD_INPUTSCREEN_DATA"
export const UPDATE_STOP_AND_POI_DATA = "UPDATE_STOP_AND_POI_DATA"
//-----UI-------
export const UPDATE_ROUTEMGMT_STATE = "UPDATE_ROUTEMGMT_STATE"
export const LOAD_STOP_AND_POI_MANAGER_STATE = "LOAD_STOP_AND_POI_MANAGER_STATE"
export const UPDATE_INPUT_SCREEN_STATE = "UPDATE_INPUT_SCREEN_STATE";
export const UPDATE_SIMULATOR_SELECTION_STATE = "UPDATE_SIMULATOR_SELECTION_STATE";
export const DATA_UPDATE_COMPONENT = "DATA_UPDATE_COMPONENT";
export const DATA_ADD_NEW_COMPONENT = "DATA_ADD_NEW_COMPONENT";